// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHAZL5XgPGz1HoPIaKBxckDcXtswXpeJY',
    appId: '1:748430858441:web:a3451d3d6951386bd69518',
    messagingSenderId: '748430858441',
    projectId: 'mydebtsapp-2cda3',
    authDomain: 'mydebtsapp-2cda3.firebaseapp.com',
    storageBucket: 'mydebtsapp-2cda3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsrWf2NNpzXG-KADeQX3NWEA2zQAmnvwk',
    appId: '1:748430858441:android:f7412adddc4f8b38d69518',
    messagingSenderId: '748430858441',
    projectId: 'mydebtsapp-2cda3',
    storageBucket: 'mydebtsapp-2cda3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtt4fyPIYK23KWFyHuXyeTaP34DHKknG4',
    appId: '1:748430858441:ios:376964186734bf64d69518',
    messagingSenderId: '748430858441',
    projectId: 'mydebtsapp-2cda3',
    storageBucket: 'mydebtsapp-2cda3.firebasestorage.app',
    iosBundleId: 'com.example.debtsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtt4fyPIYK23KWFyHuXyeTaP34DHKknG4',
    appId: '1:748430858441:ios:376964186734bf64d69518',
    messagingSenderId: '748430858441',
    projectId: 'mydebtsapp-2cda3',
    storageBucket: 'mydebtsapp-2cda3.firebasestorage.app',
    iosBundleId: 'com.example.debtsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHAZL5XgPGz1HoPIaKBxckDcXtswXpeJY',
    appId: '1:748430858441:web:f972010a708ffbafd69518',
    messagingSenderId: '748430858441',
    projectId: 'mydebtsapp-2cda3',
    authDomain: 'mydebtsapp-2cda3.firebaseapp.com',
    storageBucket: 'mydebtsapp-2cda3.firebasestorage.app',
  );
}
